version: "3.2"
services:
  apache:
    build: './docker/apache/'
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html/:Z"
  mysql:
    image: mysql:8.0.22
    environment:
      MYSQL_DATABASE: "pinboard_db"
      MYSQL_USER: "first-class-access"
      MYSQL_PASSWORD: "1DasManSichMerkenKann.Bitte?"
      MYSQL_ROOT_PASSWORD: "Noch1DasManSichMerkenKann!"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - "mysqldb:/var/lib/mysql:rw"
volumes:
  mysqldb: {}
